image:  
  repository: giorgim14/complete-devops-project
  tag: d8757aa
  pullPolicy: IfNotPresent  
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: false