image:  
  repository: giorgim14/complete-devops-project
  tag: 72bd104
  pullPolicy: IfNotPresent  
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoScalling:
  enabled: false